name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: maven_repository
          key: local-maven-${{ hashFiles('scripts/install-metabase-jar.sh') }}
          restore-keys: |
            local-maven-

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: latest

      - name: Log Clojure versions
        run: |
          java --version
          clojure --version
          lein --version

      - name: Install Metabase
        run: ./scripts/install-metabase-jar.sh

      - name: Run tests
        run: lein test

      - name: Build jar
        run: DEBUG=1 lein uberjar 

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: exasol.metabase-driver.jar
          path: target/uberjar/exasol.metabase-driver.jar
