name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      METABASE_TAG: v0.43.3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: metabase-driver

      - name: Checkout the Metabase repository at tag ${{ env.METABASE_TAG }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: metabase/metabase
          path: metabase
          ref: ${{ env.METABASE_TAG }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: latest

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('metabase-driver/deps.edn', 'metabase/**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache clj-kondo
        uses: actions/cache@v3
        with:
          path: .clj-kondo/.cache
          key: clj-kondo-cache
          restore-keys: |
            clj-kondo-cache

      - name: Log versions
        run: |
          java --version
          echo Clojure: $(clojure -M --eval "(clojure-version)")
          clojure --version

      - name: Build driver
        run: |
          cd "$GITHUB_WORKSPACE/metabase-driver"
          clojure -X:build :project-dir "\"$(pwd)\""

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: exasol.metabase-driver.jar
          path: metabase-driver/target/exasol.metabase-driver.jar
          if-no-files-found: error

      - name: Run unit tests
        run: "$GITHUB_WORKSPACE/metabase-driver/scripts/run-unit-tests.sh"

      - name: Run linter
        run: |
          cd "$GITHUB_WORKSPACE/metabase-driver"
          mkdir -p .clj-kondo/.cache
          clojure -M:clj-kondo --lint src test --debug

