name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      METABASE_VERSION: master
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: metabase-driver

      - name: Checkout the Metabase repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: metabase/metabase
          path: metabase
          ref: v${{ env.METABASE_VERSION }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: latest

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('metabase-driver/deps.edn', 'metabase/**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache clj-kondo
        uses: actions/cache@v2
        with:
          path: .clj-kondo/.cache
          key: clj-kondo-cache
          restore-keys: |
            clj-kondo-cache

      - name: Log versions
        run: |
          java --version
          echo Clojure: $(clojure -M --eval "(clojure-version)")
          clojure --version

      - name: Prepare Metabase deps
        run: |
          cd "$GITHUB_WORKSPACE/metabase"
          source "./bin/prep.sh"
          prep_deps

      - name: Build driver
        run: |
          cd "$GITHUB_WORKSPACE/metabase-driver"
          clojure -X:dev:build
          unzip -l target/exasol.metabase-driver.jar

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: exasol.metabase-driver.jar
          path: target/uberjar/exasol.metabase-driver.jar

#      - name: Run tests
#        run: lein test
#
#      - name: Run linter
#        run: |
#          mkdir -p .clj-kondo/.cache
#          lein lint

