name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: |
          sudo apt install clojure leiningen -y

      - name: Log versions
        run: |
          java --version
          echo Clojure: $(clojure --eval "(clojure-version)")
          echo Leiningen: $(lein --version)


      - name: Run tests
        run: lein test

